### ISSUE TITLE
Launchpad team membership not picked up by `charm whoami`

### ISSUE THREAD

**Issue by jamesbeedy** [juju/charmstore-client#33]
ubuntu release -> wily
charm version -> charm-tools 2.0.0
charm to push -> https://code.launchpad.net/~jamesbeedy/charms/trusty/kibana/trunk
launchpad team -> https://launchpad.net/~bdx-dev/

I would expect to see my membership to team ~bdx-dev show up here, but it doesn't. I don't seem to be able to charm push to anything :-(

I have tried logging in and back out, and removing my ~/.go-cookies, neither of which seemed to work in getting `charm whoami` to recognize my membership. 

[local.lxd-test] bdx@dev-deployer:~/allcode/charms/trusty/kibana
$ charm whoami
User: jamesbeedy
Group membership: charm-contributors, contributor-agreement-canonical

[local.lxd-test] bdx@dev-deployer:~/allcode/charms/trusty/kibana
$ charm push . cs:~bdx-dev/kibana
ERROR cannot post archive: unauthorized: access denied for user "jamesbeedy"

**Comment by marcoceppi** [comment]
@jamesbeedy there were several more updates to the charm and charm-tools commands (2.1.0 and 2.1.2 respectively) could you upgrade, run charm logout / charm login and see if whoami does what you expect?

**Comment by jrwren** [comment]
I noticed the bdx-dev team is also about 22hrs old, around the time this bug is filed.

Charmstore gets a copy of groups that you are in when you login. It is likely that when you logged into Charmstore using USSO that the group didn't exist and you are still using that Charmstore credential. To ensure that you will be redirected to USSO, visit http://www.jujucharms.com/logout and then sign in again. This should refresh the groups of which Charmstore knows you are a member.

**Comment by jamesbeedy** [comment]
Awesome. Looks like I'm in business now. Thanks!

**Comment by jamesbeedy** [comment]
Errrrrgg .... So, now I can see the `bdx-dev` team populate when I `charm whoami`, but I don't seem to be able to push to it still .... e.g.

$ charm push . cs:~bdx-dev/trusty/kibana
url: cs:~bdx-dev/kibana-0
channel: unpublished
ERROR no matching charm or bundle for cs:~bdx-dev/trusty/kibana

**Comment by frankban** [comment]
The error above should have been fixed in recent versions of the charm command. Please reopen this if that's not the case.
