### ISSUE TITLE
Enable charm version command.

### ISSUE THREAD

**Issue by frankban** [juju/charmstore-client#78]
Both `charm --version` and `charm version`.

**Comment by marcoceppi** [comment]
Please only do `charm --version`, `charm version` is already provided by charm-tools

```
marco@T430:~$ charm version
charm 2.1.1-0ubuntu1
charm-tools 2.1.2
```

**Comment by frankban** [comment]
I have a branch ready that add both. I am not so keen on having version and --version implemented in two different code bases and potentially being not kept in sync.

**Comment by marcoceppi** [comment]
When `--version` is implemented in charm, I will use it to query version in charm-tools. Because we package charm-tools silently now, there's no unified way to query status. This makes reporting issues against charm-tools and charmstore-client tedious.

All I'm asking is that the version subcommand remain in charm-tools and only have `--version` implemented in charm.

**Comment by frankban** [comment]
Please see my comment at https://github.com/juju/charmstore-client/pull/77
