### ISSUE TITLE
charm push fails in bzr branch

### ISSUE THREAD

**Issue by mitechie** [juju/charmstore-client#90]
charm 2.2.0-0ubuntu1~ubuntu16.04.1~ppa2
charm-tools 2.1.4

I'm trying to push a charm to the store, and I'm sitting in the bzr branch checkout when I do this:

$ charm push . cs:~ahasenack/landscape-server
url: cs:~ahasenack/landscape-server-1
channel: unpublished
## ERROR cannot parse bzr log: cannot parse bzr log entry: invalid revision number "364 [merge]"

revno: 364 [merge]
revision-id: landscape_builder-20160831105657-rpkna1kdoq1qa4a6
...

All "revno" fields in the bzr log output have [merge].

Workaround is to export the branch to a directory I guess and try from there, but this was unexpected. What is charm push trying to use this information for, some sort of metadata for the juju store?

from: https://bugs.launchpad.net/ubuntu/+source/charm-tools/+bug/1621870

**Comment by mhilton** [comment]
I just came here to report the same.

$ charm push . haproxy
url: cs:~martin-hilton/haproxy-1
channel: unpublished

## ERROR cannot parse bzr log: cannot parse bzr log entry: invalid revision number "105 [merge]"

revno: 107
revision-id: martin.hilton@canonical.com-20161024173734-jj8y7e93xu4d2zqa
parent: martin.hilton@canonical.com-20161010125237-noe1rmmru8xwkjd5
committer: Martin Hilton martin.hilton@canonical.com
branch nick: charm-haproxy
timestamp: Mon 2016-10-24 18:37:34 +0100
message:

##   check_haproxy: Get the "stats socket" from the configuration

revno: 106
revision-id: martin.hilton@canonical.com-20161010125237-noe1rmmru8xwkjd5
parent: danilo@canonical.com-20160920130327-35c5s16y9v1fq1gb
committer: Martin Hilton martin.hilton@canonical.com
branch nick: charm-haproxy
timestamp: Mon 2016-10-10 13:52:37 +0100
message:

##   Update check_haproxy NRPE check to support https services

revno: 105 [merge]
revision-id: danilo@canonical.com-20160920130327-35c5s16y9v1fq1gb
parent: cory.johns@canonical.com-20160721154445-yal4pu4ytk054es8
parent: danilo@canonical.com-20160916134532-na1gie1tms7zmd1h
committer: Danilo Šegan danilo@canonical.com
branch nick: trunk
timestamp: Tue 2016-09-20 15:03:27 +0200
message:
  Merge lp:~danilo/charm-haproxy/ssl-default-bind-options [r=sparkiegeek,free]

  Expose global "ssl-default-bind-options" as a configuration option to allow disabling TLS 1.0.

##   To keep backwards compatibility, this option is not required.

revno: 104 [merge]
revision-id: cory.johns@canonical.com-20160721154445-yal4pu4ytk054es8
parent: cory.johns@canonical.com-20160407151443-52jh5xd6qqlsc9b1
parent: james.jesudason@canonical.com-20160708083708-yu8oj8eokpmitfin
committer: Cory Johns cory.johns@canonical.com
branch nick: haproxy
timestamp: Thu 2016-07-21 11:44:45 -0400
message:

##   [jamesj,r=johnsca] Add support for Xenial

revno: 103 [merge]
revision-id: cory.johns@canonical.com-20160407151443-52jh5xd6qqlsc9b1
parent: adam.israel@gmail.com-20160304161931-r2en00ue80mj2rfr
parent: guillermo.gonzalez@canonical.com-20160303201422-2p3nh2cp58r1pupl
committer: Cory Johns cory.johns@canonical.com
branch nick: haproxy
timestamp: Thu 2016-04-07 11:14:43 -0400
message:

##   [verterok] Add statistics relation

revno: 102 [merge]
revision-id: adam.israel@gmail.com-20160304161931-r2en00ue80mj2rfr
parent: adam.israel@gmail.com-20160303164714-9n33kff5mgyjre3v
parent: samantha.jian-pielak@canonical.com-20160212183048-zw8mtgk4979ykojv
committer: Adam Israel adam.israel@gmail.com
branch nick: haproxy
timestamp: Fri 2016-03-04 11:19:31 -0500
message:

##   [samantha-jian] Add liberty support

revno: 101
revision-id: adam.israel@gmail.com-20160303164714-9n33kff5mgyjre3v
parent: marco@ceppi.net-20160109164237-hbxznsy3gx6tb4cr
committer: Adam Israel adam.israel@gmail.com
branch nick: haproxy
timestamp: Thu 2016-03-03 11:47:14 -0500
message:

##   [aisrael] Fix lint error

revno: 100
revision-id: marco@ceppi.net-20160109164237-hbxznsy3gx6tb4cr
parent: kevin.monroe@canonical.com-20151119181343-wqyvwduc3d7rj60n
committer: Marco Ceppi marco@ceppi.net
branch nick: haproxy
timestamp: Sat 2016-01-09 17:42:37 +0100
message:

##   New icon

revno: 99 [merge]
revision-id: kevin.monroe@canonical.com-20151119181343-wqyvwduc3d7rj60n
parent: christopher.glass@canonical.com-20151021154718-6pukhv1gc9wx9why
parent: guillermo.gonzalez@canonical.com-20151104141216-c43fpa0fa6dgcs2v
committer: Kevin W. Monroe kevin.monroe@canonical.com
branch nick: haproxy
timestamp: Thu 2015-11-19 18:13:43 +0000
message:

##   [verterok, r=admcleod, a=kwmonroe] restart rsyslog if haproxy config changes; minor updates to tests

revno: 98 [merge]
revision-id: christopher.glass@canonical.com-20151021154718-6pukhv1gc9wx9why
parent: christopher.glass@canonical.com-20150818110648-0u58qkqxopfjc0sy
parent: christopher.glass@canonical.com-20151016093942-mcef6uv8ad3v4eai
committer: Christopher Glass christopher.glass@canonical.com
branch nick: haproxy
timestamp: Wed 2015-10-21 17:47:18 +0200
message:
  Merge lp:~tribaal/charms/trusty/haproxy/longer-openssl-selfsigned [a=tribaal] [r=dpb]

  Make the self-signed SSL certificate last for 3650 days instead of the default of 30 days.

##   This mirrors what the apache charm does.

Use --include-merged or -n0 to see merged revisions.

However it should be noted that the charm is still uploaded.

**Comment by mhilton** [comment]
This was released in, or before, 2.2.3
